### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by gsbecerra** [MicrochipTech/aws-iot-firmware-pic32mz#11]
I can't connect the board to AWS-iot following the instructions, the Insight on Things App works, but with the board I always get the LED 1, 5 and 6 on ("Connection Issue, no internet found"). I don't know how to configure the board with the credentials and certs, the instructions don't tell anything about it.

**Comment by bellhop** [comment]
We are in the process of releasing version v2.0.0 of the Insight on Things app that will handle these for you.  In the meantime I would suggest that you version v1.3.1 of our tool and the instructions with it.

Here is the link https://github.com/MicrochipTech/aws-iot-firmware-pic32mz/releases/tag/v1.3.1

We plan to release versionv 2.0.0 of the Insight on Things app that is required for version v2.0.0 firmware by the end of next week. (2017-01-13).  I will reply to this issue once that has been posted.

**Comment by gsbecerra** [comment]
thank you, great answer, it is working now.

**Comment by Oakeson** [comment]
Looking forward to the v2.0.0 update, thanks!

**Comment by bellhop** [comment]
@Oakeson - The v2.0.0 of the __Insight on Things__ desktop application has been posted [here](https://github.com/MicrochipTech/aws-iot-insight-on-things-desktop-app/releases)

**Comment by Oakeson** [comment]
@bellhop - Got it - looks good, thanks!
