### ISSUE TITLE
out of box instructions don't work

### ISSUE THREAD

**Issue by mrpackethead** [MicrochipTech/aws-iot-firmware-pic32mz#4]

**Comment by ghost** [comment]
Thank you for the feedback,

What part of the OoB instructions failed to work?  We would like to narrow it down in order to fix it as soon as possible.

**Comment by mrpackethead** [comment]
In step 3,  this line;

aws iot attach-principal-policy --principal-arn '<certificate-arn>' --policy-name 'MQTTandShadowPolicy'

--princial-arm is not a valid option.  It should be just --princial.

**Comment by ghost** [comment]
Yes this is correct, we will fix this in an update.
